#!/bin/bash
#====================================================
# SCRIPT: ELH SERVER QUICK DEPLOY FOR X-UI
# DEVELOPED BY: MONOXOFIGHTER
# UPDATE DATE: 2022.02.25
# THIS REPO SPECIALLY MADE FOR DARKSSH FREE SERVERS.
#====================================================

# Update System
sudo apt update 
# Upgrade System
sudo apt upgrade -y
# Uninstall X-UI
systemctl stop x-ui
systemctl disable x-ui
rm /etc/systemd/system/x-ui.service -f
systemctl daemon-reload
systemctl reset-failed
rm /etc/x-ui/ -rf
rm /usr/local/x-ui/ -rf
rm /usr/bin/x-ui -f
# Reinstall
bash <(curl -Ls https://raw.githubusercontent.com/vaxilu/x-ui/master/install.sh)
# Reboot
sudo reboot
